"""Cached, read-only loaders for research artifacts.

The analysis layer under paper/analysis/ is regenerated by another process while the demo
runs. Every cached value is keyed on the mtimes of its source files, so a rebuilt artifact
is picked up on the next request; if a source is briefly missing or half-written, the last
good value is served instead of failing.
"""

from __future__ import annotations

import ast
import json
import logging
import struct
import threading
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple

import pandas as pd

from app.data import paths as P

log = logging.getLogger("wildpalm.loaders")


class _MtimeCache:
    def __init__(self) -> None:
        self._entries: Dict[str, Tuple[tuple, Any]] = {}
        self._locks: Dict[str, threading.Lock] = {}
        self._guard = threading.Lock()

    def _lock(self, key: str) -> threading.Lock:
        with self._guard:
            return self._locks.setdefault(key, threading.Lock())

    @staticmethod
    def _signature(sources: Iterable[Path]) -> tuple:
        sig = []
        for path in sources:
            try:
                sig.append((str(path), path.stat().st_mtime_ns))
            except FileNotFoundError:
                sig.append((str(path), None))
        return tuple(sig)

    def get(self, key: str, sources: List[Path], build: Callable[[], Any]) -> Any:
        with self._lock(key):
            sig = self._signature(sources)
            entry = self._entries.get(key)
            if entry is not None and entry[0] == sig:
                return entry[1]
            try:
                value = build()
            except Exception:
                if entry is not None:
                    log.warning("rebuild of %s failed; serving previous value", key, exc_info=True)
                    return entry[1]
                raise
            self._entries[key] = (sig, value)
            return value


CACHE = _MtimeCache()


def read_csv(path: Path, **kwargs: Any) -> pd.DataFrame:
    key = f"csv:{path}:{sorted(kwargs.items())!r}"
    return CACHE.get(key, [path], lambda: pd.read_csv(path, **kwargs))


def read_json(path: Path) -> Any:
    return CACHE.get(f"json:{path}", [path], lambda: json.loads(path.read_text()))


def analysis_csv(*parts: str, **kwargs: Any) -> Optional[pd.DataFrame]:
    path = P.ANALYSIS_OUT.joinpath(*parts)
    if not path.is_file():
        return None
    return read_csv(path, **kwargs)


# ---------------------------------------------------------------------------
# Analysis-layer registry (paper/analysis/scripts/common.py), parsed statically.
# The module is never imported or executed: only literal assignments are read.
# ---------------------------------------------------------------------------
_RUN_ARGS = ("model_key", "display", "family", "nominal_size", "nominal_b", "rel", "checkpoint", "expected")
_REGISTRY_NAMES = ("LADDERS", "CORE_PANEL", "PAIR_GROUPS", "PAIR_GROUP_NOTES", "NOT_RUN",
                   "CONDITION_POLICY", "KNOWN_EXCLUSIONS")


def _parse_common() -> Dict[str, Any]:
    tree = ast.parse(P.COMMON_PY.read_text())
    out: Dict[str, Any] = {"RUNS": []}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or len(node.targets) != 1:
            continue
        target = node.targets[0]
        if not isinstance(target, ast.Name):
            continue
        name = target.id
        if name == "RUNS" and isinstance(node.value, ast.List):
            for call in node.value.elts:
                if not (isinstance(call, ast.Call) and getattr(call.func, "id", None) == "_run"):
                    continue
                try:
                    values = [ast.literal_eval(a) for a in call.args]
                    kw = {k.arg: ast.literal_eval(k.value) for k in call.keywords}
                except ValueError:
                    continue
                run = dict(zip(_RUN_ARGS, values))
                run["eval_key"] = kw.get("eval_key", run.get("model_key"))
                out["RUNS"].append(run)
        elif name in _REGISTRY_NAMES:
            try:
                out[name] = ast.literal_eval(node.value)
            except ValueError:
                log.warning("could not parse %s from common.py", name)
    return out


def analysis_registry() -> Dict[str, Any]:
    return CACHE.get("registry", [P.COMMON_PY], _parse_common)


# ---------------------------------------------------------------------------
# Detection cohort
# ---------------------------------------------------------------------------
def _png_size(path: Path) -> Tuple[int, int]:
    with path.open("rb") as f:
        header = f.read(24)
    if header[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"not a PNG: {path}")
    w, h = struct.unpack(">II", header[16:24])
    return int(w), int(h)


def _build_detections() -> pd.DataFrame:
    idx = pd.read_csv(P.INDEX_CSV, dtype={"sample_id": str, "image_name": str})
    with ThreadPoolExecutor(max_workers=16) as pool:
        sizes = list(pool.map(lambda p: _png_size(P.DATASET_DIR / p), idx["image_path"]))
    idx["image_width"] = [s[0] for s in sizes]
    idx["image_height"] = [s[1] for s in sizes]
    # Same definition and quintiles as paper/analysis common.detection_properties().
    idx["norm_area"] = idx["bbox_area"] / (idx["image_width"] * idx["image_height"])
    q = [f"Q{i}" for i in range(1, 6)]
    idx["confidence_q"] = pd.qcut(idx["confidence"], 5, labels=q).astype(str)
    idx["area_q"] = pd.qcut(idx["norm_area"], 5, labels=q).astype(str)

    samples = sample_table()
    geo = (samples.drop_duplicates("sample_id").set_index("sample_id")[["matched_gt", "max_iou"]])
    idx = idx.join(geo, on="sample_id")

    review = pd.read_csv(P.HUMAN_REVIEW_CSV, dtype={"sample_id": str})
    idx = idx.join(review.set_index("sample_id")[["semantic_label"]], on="sample_id")

    joined = P.ANALYSIS_OUT / "semantic" / "unmatched_review_joined.csv"
    if joined.is_file():
        reasons = pd.read_csv(joined, dtype={"sample_id": str}).set_index("sample_id")
        idx = idx.join(reasons[["unmatched_reason_geometric"]], on="sample_id")
    else:
        idx["unmatched_reason_geometric"] = None

    counts = idx.groupby("image_name")["sample_id"].transform("count")
    idx["detections_in_image"] = counts
    return idx.set_index("sample_id", drop=False)


def detections() -> pd.DataFrame:
    sources = [P.INDEX_CSV, P.SAMPLE_TABLE, P.HUMAN_REVIEW_CSV,
               P.ANALYSIS_OUT / "semantic" / "unmatched_review_joined.csv"]
    return CACHE.get("detections", sources, _build_detections)


# ---------------------------------------------------------------------------
# Sample-level VLM decisions (valid rows of usable cells; parse-error rows are absent)
# ---------------------------------------------------------------------------
def sample_table() -> pd.DataFrame:
    return CACHE.get(
        "sample_table", [P.SAMPLE_TABLE],
        lambda: pd.read_csv(P.SAMPLE_TABLE, dtype={"sample_id": str, "image_id": str}),
    )


def _build_decision_lookup() -> Dict[str, Dict[Tuple[str, str], str]]:
    df = sample_table()
    lookup: Dict[str, Dict[Tuple[str, str], str]] = {}
    for sid, mk, cond, dec in zip(df["sample_id"], df["model_key"], df["condition"], df["decision"]):
        lookup.setdefault(sid, {})[(mk, cond)] = dec
    return lookup


def decision_lookup() -> Dict[str, Dict[Tuple[str, str], str]]:
    """sample_id -> {(model_key, condition): decision}."""
    return CACHE.get("decision_lookup", [P.SAMPLE_TABLE], _build_decision_lookup)


# ---------------------------------------------------------------------------
# LabelMe annotations (Protocol v2 GT box rule)
# ---------------------------------------------------------------------------
def labelme_palm_boxes(image_name: str) -> Dict[str, Any]:
    """Protocol v2 GT boxes for one patch: shapes whose label is 'palm' (case/space-insensitive),
    box = axis-aligned envelope of all shape points (see outputs/evaluation_protocol_v2/PROTOCOL.json).
    """
    path = P.RAW_PATCHES_ROOT / f"{image_name}.json"

    def build() -> Dict[str, Any]:
        if not path.is_file():
            return {"available": False, "boxes": [], "image_width": None, "image_height": None}
        data = json.loads(path.read_text())
        boxes = []
        for shape in data.get("shapes", []):
            label = shape.get("label")
            if not (isinstance(label, str) and label.strip().lower() == "palm"):
                continue
            pts = shape.get("points") or []
            if not pts:
                continue
            xs = [float(p[0]) for p in pts]
            ys = [float(p[1]) for p in pts]
            boxes.append([min(xs), min(ys), max(xs) - min(xs), max(ys) - min(ys)])
        return {"available": True, "boxes": boxes,
                "image_width": data.get("imageWidth"), "image_height": data.get("imageHeight")}

    return CACHE.get(f"labelme:{image_name}", [path], build)
